### ISSUE TITLE
rxLogisticRegression exception while shutting down RxClientPipe

### ISSUE THREAD

**Issue by 011gwerc01** [MicrosoftDocs/machine-learning-server-docs#25]
I'm getting the following error message 

"exception while shutting down RxClientPipe: Write error: expected 8 got _4294967295"

when executing the sample code:

`# Multi-class logistic regression`
`testObs <- rnorm(nrow(iris)) > 0`
`testIris <- iris[testObs,]`
`trainIris <- iris[!testObs,]`
`multiLogit <- rxLogisticRegression( formula = Species~Sepal.Length + Sepal.Width + Petal.Length + Petal.Width, type = "multiClass", data = trainIris)`
`# Score the model score`
`MultiDF <- rxPredict(multiLogit, data = testIris, extraVarsToWrite = "Species") `
`# Print the first rows of the data frame with scores`
`head(scoreMultiDF)`
`# Look at confusion matrix`
`table(scoreMultiDF$Species, scoreMultiDF$PredictedLabel)`
`# Look at the observations with incorrect predictions`
`badPrediction = scoreMultiDF$Species != scoreMultiDF$PredictedLabel`
`scoreMultiDF[badPrediction,]`

**Comment by HeidiSteen** [comment]
Could you post this question to the forums?  This is the link:  
https://social.msdn.microsoft.com/Forums/en-US/home?forum=MicrosoftR
