### ISSUE TITLE
Server Compatibility

### ISSUE THREAD

**Issue by abbgrade** [MicrosoftDocs/machine-learning-server-docs#36]
The documentation page [Server Compatibility](https://github.com/MicrosoftDocs/machine-learning-server-docs/blob/live/microsoft-r/r-client/compatibility-with-server.md) would benefit from links to the downloads to the old versions of Microsoft R Client.

**Comment by jeroenterheerdt** [comment]
Not sure if that is a good idea as the best practice is so make sure your R Client follows your Server release.

**Comment by abbgrade** [comment]
And that's why it's good to be able to download a old client, if your server is not the latest.

**Comment by jeroenterheerdt** [comment]
Thanks, I am looking into it now.

**Comment by jeroenterheerdt** [comment]
@abbgrade: I am happy to inform you that we have updated the [Server Compatibility page](https://docs.microsoft.com/en-us/machine-learning-server/r-client/compatibility-with-server) with the links to older client releases. Thanks for reporting!
