### ISSUE TITLE
Update to R Client for use with 3.5.x

### ISSUE THREAD

**Issue by dfrizzell** [MicrosoftDocs/machine-learning-server-docs#62]
When will an R Client version be released that can work with more recent versions of R Open. Specifically when will the R Client be compatible with a 3.5.x version of R Open. 

We need an update to this product, as it has not been updated since February 2018.

**Comment by jeroenterheerdt** [comment]
Hi @dfrizzell since this question is product related, I invite you to post the question at [our forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=MicrosoftR). This repo is only for documentation related discussion. Thanks.
