### ISSUE TITLE
Provide more details on Python service deployment

### ISSUE THREAD

**Issue by cmmardyla** [MicrosoftDocs/machine-learning-server-docs#65]
It would be immensely beneficial if this document provided more information on how a Python service is deployed, beyond the single example given at https://github.com/Microsoft/ML-Server-Python-Samples/blob/master/operationalize/Quickstart_Publish_Python_Web_Service.ipynb. 
As far as I can see, the following questions are not answered in the documentation.

- If deploying a Python model referencing code in several Python files, where should the referenced Python files be stored so that the deployed model can find them? (For example, say I'm deploying a Python function to do basic arithmetic. The deployed model calls a function "add" from the file add-util.py. Where should add-util.py be stored?)
- Where is a deployed model stored in the machine learning server? 
- When defining a Python service to deploy (as in the link above), what is the difference between the code_fn function and models function? 
- There is documentation on offline R package installs, but nothing for offline Python packages installs (from a whl file, probably). Can this be added?

If there is existing documentation on any of these questions, please redirect me.

**Comment by jeroenterheerdt** [comment]
which page are you referring to?

**Comment by cmmardyla** [comment]
I am referring to the following pages
- https://docs.microsoft.com/en-us/machine-learning-server/operationalize/python/quickstart-application-integration-with-swagger 
- https://docs.microsoft.com/en-us/machine-learning-server/install/machine-learning-server-windows-packages

**Comment by garyericson** [comment]
FYI, I added this to our documentation backlog. #please-close

**Comment by davidpeterh** [comment]
Thank you @garyericson
