### ISSUE TITLE
DSVM R Version 3.4.3 and mrsdeploy

### ISSUE THREAD

**Issue by sqlshep** [MicrosoftDocs/machine-learning-server-docs#66]
I am using a Data Science Virtual Machine that has "version.string R version 3.4.3 (2017-11-30)" installed which according to mrsdeploy documentation is what is required to install the package.   Is the documentation out of date? I have created an enterprise configuration using your instructions and have no way to log into it. 

I receive 
> install.packages("mrsdeploy")
Warning in install.packages :
  package ‘mrsdeploy’ is not available (for R version 3.4.3)

**Comment by jeroenterheerdt** [comment]
can you share some more details on the commands that you ran?

**Comment by sqlshep** [comment]
Sorry, Basically, follow the instructions

https://docs.microsoft.com/en-us/machine-learning-server/operationalize/configure-machine-learning-server-one-box

##### With elevated privileges, run the following commands.
##### Set up both nodes on one machine
az ml admin node setup --onebox --admin-password <Password> --confirm-password <Password>

##### Check that the nodes are now running
az ml admin node list

##### Authenticate via CLI
##### Account name is `admin` if LDAP or AAD is not set up.
az login --mls

**Comment by rajmera3** [comment]
Hi @sqlshep  - I apologize for the late response.

If you are using the R that comes with mlserver, there is no need to install that package yourself. It is already included. mrsdeploy is not in a public repository, so trying to install it will result in that warning / error.

While it is installed, it is not loaded. You can do so by typing `library(mrsdeploy)`.
More information on mrsdeploy can be found here: [mrsdeploy package for R](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmachine-learning-server%2Fr-reference%2Fmrsdeploy%2Fmrsdeploy-package&data=02%7C01%7CRahul.Ajmera%40microsoft.com%7C4418844704ae477ccfef08d777799b0b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637109236477521873&sdata=qYS8MDWsgA9zU33233qlr0Az6UJ9LjGdzExjnkmseH0%3D&reserved=0)

**Comment by davidpeterh** [comment]
Thanks @rajmera3 for the response - closing the issue.
