### ISSUE TITLE
error in coefLabelStyle

### ISSUE THREAD

**Issue by brunobertora** [MicrosoftDocs/machine-learning-server-docs#69]
hello everyone!
Maybe (and probably) I'm wrong, but I think that the component "coefLabelStyle" produces an error when you select coefLabelStyle="R".
I was testing the results of each level between rxGlm and glm, and I figured out that when you have no observations in one of the levels then rxGlm mix the other factor values.

**Comment by garyericson** [comment]
@brunobertora - Thanks for this. Can you tell me in what article you saw this being used?

**Comment by brunobertora** [comment]
Hello Gary,
I don't understand what do you mean about "article"!. I was only testing the two formulas in R: glm and rxGlm.
I found out this issue because I wanted to obtain the same coefLabelStyle to compare both formulas. You can find this typing ?rxGlm in R or in :
https://docs.microsoft.com/en-us/machine-learning-server/r-reference/revoscaler/rxglm
I hope this can help you.
I also have some comments about differences in the standard error between "glm" and "rxGlm" formula. (you probably know that).



[https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png]<https://docs.microsoft.com/en-us/machine-learning-server/r-reference/revoscaler/rxglm>
rxGlm function (revoAnalytics) | Microsoft Docs<https://docs.microsoft.com/en-us/machine-learning-server/r-reference/revoscaler/rxglm>
Use rxGlm to fit generalized linear regression models for small or large data. Any valid glm family object can be used.
docs.microsoft.com




________________________________
De: Gary Ericson <notifications@github.com>
Enviado: miércoles, 18 de diciembre de 2019 07:58 p. m.
Para: MicrosoftDocs/machine-learning-server-docs <machine-learning-server-docs@noreply.github.com>
CC: brunobertora <brunobertora@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [MicrosoftDocs/machine-learning-server-docs] error in coefLabelStyle (#69)


@brunobertora<https://github.com/brunobertora> - Thanks for this. Can you tell me in what article you saw this being used?

**Comment by garyericson** [comment]
@rajmera3 @ronychatterjee - Could one of you look at this and respond?

@dphansen

**Comment by garyericson** [comment]
@brunobertora - I'm sorry, but I see that no one ever responded to this. If you're still looking for an answer, I would recommend posting this question on the Microsoft forum, [Microsoft Q & A](https://docs.microsoft.com/en-us/answers/products/sql-server). A large number of technical experts monitor the forum. I am going to go ahead and close this thread.
