### ISSUE TITLE
Base Url

### ISSUE THREAD

**Issue by imshreya** [MicrosoftDocs/machine-learning-server-docs#70]
What would be the base url for the request to find the Access Token?
The body seems to contain the username & password. Is there any other detail that needs to be passed in the body?

**Comment by garyericson** [comment]
@imshreya - I'm sorry, but I see that no one ever responded to your question. If you're still looking for an answer, I would recommend posting this question on the Microsoft forum, [Microsoft Q & A](https://docs.microsoft.com/en-us/answers/products/sql-server). A large number of technical experts monitor the forum and you're more likely to get an answer there. I'm going to go ahead and close this thread.
