### ISSUE TITLE
Error in running LOS vignette for rxFastTrees

### ISSUE THREAD

**Issue by mkrasmus** [MicrosoftDocs/machine-learning-server-docs#71]
Hi

Whilst running step3_training_evaluation.R code from:
[r-server-hospital-length-of-stay](https://microsoft.github.io/r-server-hospital-length-of-stay/data-scientist.html)

Cannot find anything on MicrosoftRML package. Is this a typo in the code?

See error message

> Error in rxTlcBridge(formula = lengthofstay ~ rcount + gender + dialysisrenalendstage +  : 
>   MicrosoftRML package must be installed. 
> Calls: source ... eval -> eval -> rxRemoteCall -> do.call -> rxTlcBridge 
> Execution halted 
> Error in rxCompleteClusterJob(hpcServerJob, consoleOutput, autoCleanup) : 
>   No results available - final job state: failed
> > Train the Boosted Trees model.
> > boosted_model <- rxFastTrees(formula = formula,
>                               data = LoS_Train,
>                               type = c("regression"),
>                               numTrees = 40,
>                               learningRate = 0.2,
>                              splitFraction = 5/24,
>                               featureFraction = 1,
>                               minSplit = 10)	
> XXX ( process  1 ) has started run at  2020-03-16 15:45:44.41  ====== 
> Error in rxTlcBridge(formula = lengthofstay ~ rcount + gender + dialysisrenalendstage +  : 
>   MicrosoftRML package must be installed. 
> Calls: source ... eval -> eval -> rxRemoteCall -> do.call -> rxTlcBridge 
> Execution halted 
> Error in rxCompleteClusterJob(hpcServerJob, consoleOutput, autoCleanup) : 
>   No results available - final job state: failed

**Comment by garyericson** [comment]
@mkrasmus - I'm sorry, but I see that no one ever responded to your question. If you're still looking for an answer, I would recommend posting this question on the Microsoft forum, [Microsoft Q & A](https://docs.microsoft.com/en-us/answers/products/sql-server). A large number of technical experts monitor the forum and you're more likely to get an answer there. I'm going to go ahead and close this thread.

#please-close
